config/routes.rb
  Rails.application.routes.draw do
  root "weather#index"
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get "weather" => "weather#index"
  get '/twitter' => 'pages#twitter'
  get "/searchs" => "searchs#index"
  get "/" => "weather#index"
  post "/" => "weather#enterPostcode"
  resources :places

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ActiveRecord::Base
    geocoded_by :address
    after_validation :geocode, if: ->(obj){obj.address.present? and obj.address_changed?}
end

app/models/request.rb
class Request < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  def about
  end
  
  def contact
  end  
  
  def twitter
  end  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.order('created_at DESC')
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Place added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def place_params
    params.require(:place).permit(:title, :address,)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @allRequest = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name, :city, :sky, :postcode, :temp)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def index
		@allRequest = Request.all
	end
end

app/controllers/weather_controller.rb
require 'weather-api'
require 'rubygems'

class WeatherController < ApplicationController
  protect_from_forgery with: :null_session
  def index
	puts "--------------- In Index -----------------"
	@allRequest = Request.all
	puts "# of bids = #{@allRequest.size}"
	
  end

  def enterPostcode
	puts "--------------- In Enter Postcode -----------------"
	@name = params[:nameInput]
	@city = params[:locationInput]
	@response = Weather.lookup_by_location(@city, Weather::Units::CELSIUS)
	postcode = "0000000"
	@temp = @response.condition.temp.to_s
	@sky = @response.condition.text

	map = {"name" => @name, "postcode" => postcode, "city" => @city, "temp" => @temp, "sky" => @sky}
	newRow = Request.new(map)
	respond_to do |format|
		if newRow.save
			puts "Success!"
			format.html {redirect_to weather_url}
		else
			format.html {redirect_to "/"}	# Can create an error page
		end
	end
  end

 

  def handlePost
  	if params[:commit] == "Enter Info"
  		enterPostcode
  	# elsif params[:commit] == "Get Leader"
  	# 	getLeader
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather Forecast</title>
	<link rel="stylesheet" type= "text/css" href ="style.css" />
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width">
				</head>
  <body>
  	<%= render 'shared/navigation' %>
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<html>
    </body>
  <head>
    <title> Weather Forecast </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
            <%= link_to "WeatherGO", '/weather', id: "logo" %>
          <ul class="nav navbar-nav navbar-right">
             <li><%= link_to "Home",   '/weather' %></li> 
            <li><%= link_to "About",   '/about' %></li>
            <li><%= link_to "Twitter",   '/twitter' %></li>
            <li><%= link_to "Contact", '/contact' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
        <div class="center jumbotron">
<br />
<br />
<br />
<br />
<br />
  <h1>About Us</h1>

    </div>
    <h2>Tobais and I (Amos Marawa) are students at the university of aberdeen, this is our AWAD group assiagnement. The web appliction checks the weather at a specfic location at the current time of the users choosing</h2>
  </body>
<div class="navbar-header">
    
    

app/views/pages/contact.html.erb
<html>
    </body>
  <head>
    <title> Weather Forecast </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <%= link_to "WeatherGO", '/weather', id: "logo" %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '/weather' %></li> 
            <li><%= link_to "About",   '/about' %></li>
            <li><%= link_to "Twitter",   '/twitter' %></li>
            <li><%= link_to "Contact", '/contact' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
        <div class="center jumbotron">
          <br />
          <br />
          <br />
          <br />
          <br />

  <h1>Contact Details</h1>
    </div>
     <h2>Tobais email tmoney@hotmial.com phone number 0787XXXXXXXX </h2>
     <h2>Amos email example@gmail.com phone number 07654XXXXXX</h2>
  </body>
  <div class="navbar-header">

app/views/pages/twitter.html.erb
<html>
    </body>
  <head>
    <title> Weather Forecast </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <%= link_to "WeatherGO", '/weather', id: "logo" %>
          <ul class="nav navbar-nav navbar-right">
               <li><%= link_to "Home",   '/weather' %></li> 
            <li><%= link_to "About",   '/about' %></li>
            <li><%= link_to "Twitter",   '/twitter' %></li>
            <li><%= link_to "Contact", '/contact' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
        <div class="center jumbotron">
 <br />
<br />
<br />
<br />
<br />
  <h1>MetOffice Twitter Feed</h1>
    </div>
  </body>
<div class="navbar-header">
    
    
  


<a class="twitter-timeline" data-lang="en" data-height="2000" data-width= "2000" href="https://twitter.com/metoffice?ref_src=twsrc%5Etfw">Tweets by metoffice</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :sky %><br>
    <%= f.text_field :sky %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :temp %><br>
    <%= f.text_field :temp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/requests/_place.html.erb
<li>
  <%= link_to place.title, place_path(place) %>
</li>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1> Previous Weather Requests</h1>
<p><a href="http://localhost:3000/">Home</a></p>
<table cellpadding="10px" cellspacing="0px">
	<thread>
		<tr>
			<th> Name </th>
			<th> City </th>
			<th> Temperature </th>
			<th> Conditions </th>
		</tr>
	</thread>

	<tbody>
		<% @allrequest.reverse_each do |request| %>
			<tr>
				<td> <%= request.name %> </td>
				<td> <%= request.city %> </td>
				<td> <%= request.temp %> °C </td>
				<td> <%= request.sky %> </td>
				
			</tr>
		<% end %>
	</tbody>
</table>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @request.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @request.city %>
</p>

<p>
  <strong>Sky:</strong>
  <%= @request.sky %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @request.postcode %>
</p>

<p>
  <strong>Temp:</strong>
  <%= @request.temp %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/weather">Weather App</a>
      <a class="navbar-brand" href="/about">About</a>
      <a class="navbar-brand" href="/twitter">Twitter</a>
      <a class="navbar-brand" href="/contact">Contact</a>
    </div>
  </div>
</nav>

app/views/weather/index.html.erb
<div class="center jumbotron">
<br />
<br />
<br />
<br />
<br />
 <h1>Welcome to WeatherGo</h1>

  <h2>   This is our App you check the current weather of any city in the world  </h2>


<h1>Check Weather Anyhwere</h1>


<%= form_tag do%>
	<p>Your Name: <%= text_field_tag(:nameInput) %> </p>
	<p>Your City: &nbsp; &nbsp;<%= text_field_tag(:locationInput) %> </p>
	<p> <%= submit_tag "Enter Location"%>   <input type="button" value="Cancel" /> </p>
	
<% end %>

<p><%= @allRequest.last.name.titleize %> The current weather in <%= @allRequest.last.city %> is <%= @allRequest.last.temp %> degrees celsius. The conditions outside are <%= @allRequest.last.sky.downcase %>.</p>

<%= if @allRequest.last.sky == "Partly cloudy"
link_to image_tag "partlycloudy.jpg"
elsif @allRequest.last.sky == "Sunny"
	link_to image_tag "sun.png"
elsif @allRequest.last.sky == "Mostly Cloudy"
	link_to image_tag"mostlycloudy.jpg"
elsif @allRequest.last.sky == "Cloudy"
	link_to image_tag "cloudy.jpg"
elsif @allRequest.last.sky == "Snow"
	link_to image_tag "snow.png"
elsif @allRequest.last.sky == "Breezy"
	link_to image_tag "breezy.png"
elsif @allRequest.last.sky == "Rain"
	link_to image_tag "rain.png"
elsif @allRequest.last.sky == "Rain And Snow"
	link_to image_tag "rain.png"	
elsif @allRequest.last.sky == "Windy"
	link_to image_tag "breezy.png"
elsif @allRequest.last.sky == "Scattered Showers"
	link_to image_tag "rain.png"
elsif @allRequest.last.sky == "Snow Showers"
	link_to image_tag "snow.png"
else
	link_to image_tag "sun.png"
end
%>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@allRequest.last.city}&markers=#{@allRequest.last.city}&zoom=9&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
              class: 'img-fluid img-rounded', alt: "#{@allRequest.last.city} on the map"%>